const heroes = {
  abel: {
    name: "Abel",
    epithet: "The Panther",
    image: "/images/hero-portraits/abel.png",
    type: "Blue Lance",
    typeImg: "/images/weapon-icons/blue-lance.png",
    movement: "Cavalry",
    movementImg: "/images/movement-icons/cavalry.png",
    weapon: 8,
    weaponName: "Brave Lance+",
    special: "Aegis",
    skillA: "HP +5",
    skillC: "Swordbreaker 3",
    spdBonus: true,
    bonusValueSpd: -5,
    hp: [35, 39, 42],
    atk: [30, 33, 36],
    spd: [29, 32, 35],
    def: [22, 25, 28],
    res: [22, 25, 29],
    hpMin: [16, 17, 18],
    atkMin: [6, 7, 8],
    spdMin: [7, 8, 9],
    defMin: [7, 8, 9],
    resMin: [5, 6, 7],
    weaponIndex: 1,
    movementIndeex: 1
  },
  alfonse: {
    name: "Alfonse",
    epithet: "Prince of Askr",
    image: "/images/hero-portraits/alfonse.png",
    type: "Red Sword",
    typeImg: "/images/weapon-icons/red-sword.png",
    movement: "Infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 16,
    weaponName: "Fólkvangr",
    special: "Sol",
    skillA: "Death Blow 3",
    skillC: "Spur Atk 3",
    hp: [43, 43, 43],
    atk: [35, 35, 35],
    spd: [25, 25, 25],
    def: [32, 32, 32],
    res: [22, 22, 22],
    hpMin: [19, 19, 19],
    atkMin: [9, 9, 9],
    spdMin: [6, 6, 6],
    defMin: [8, 8, 8],
    resMin: [5, 5, 5],
    weaponIndex: 0,
    movementIndex: 0
  },
  alm: {
    name: "Alm",
    epithet: "Hero of Prophecy",
    image: "/images/hero-portraits/alm.png",
    type: "Red Sword",
    typeImg: "/images/weapon-icons/red-sword.png",
    movement: "Infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 16,
    weaponName: "Falchion",
    special: "Draconic Aura",
    skillA: "Attack +3",
    skillB: "Windsweep 3",
    hp: [42, 45, 48],
    atk: [30, 33, 36],
    spd: [27, 30, 33],
    def: [24, 28, 31],
    res: [19, 22, 25],
    hpMin: [20, 21, 22],
    atkMin: [8, 9, 10],
    spdMin: [5, 6, 7],
    defMin: [5, 6, 7],
    resMin: [4, 5, 6],
    weaponIndex: 0,
    movementIndex: 0
  },
  amelia: {
    name: "Amelia",
    epithet: "Rose of the War",
    image: "/images/hero-portraits/amelia.png",
    type: "Green Axe",
    typeImg: "/images/weapon-icons/green-axe.png",
    movement: "armored",
    movementImg: "/images/movement-icons/armored.png",
    weapon: 14,
    weaponName: "Slaying Axe+",
    special: "Sacred Cowl",
    skillA: "Earth Boost 3",
    skillC: "Armor March 3",
    hp: [44, 47, 50],
    atk: [31, 34, 37],
    spd: [31, 34, 37],
    def: [32, 35, 38],
    res: [20, 23, 27],
    hpMin: [18, 19, 20],
    atkMin: [5, 6, 7],
    spdMin: [7, 8, 9],
    defMin: [8, 9, 10],
    resMin: [3, 4, 5],
    weaponIndex: 2,
    movementIndex: 3
  },
  anna: {
    name: "Anna",
    epithet: "Commander",
    image: "/images/hero-portraits/anna.png",
    type: "Green Axe",
    typeImg: "/images/weapon-icons/green-axe.png",
    movement: "Infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 16,
    weaponName: "Nóatún",
    special: "Astra",
    skillB: "Vantage 3",
    skillC: "Spur Res 3",
    hp: [41, 41, 41],
    atk: [29, 29, 29],
    spd: [38, 38, 38],
    def: [22, 22, 22],
    res: [28, 28, 28],
    hpMin: [19, 19, 19],
    atkMin: [7, 7, 7],
    spdMin: [10, 10, 10],
    defMin: [5, 5, 5],
    resMin: [6, 6, 6],
    weaponIndex: 2,
    movementIndex: 0
  },
  arden: {
    name: "Arden",
    epithet: "Strong and Tough",
    image: "/images/hero-portraits/arden.png",
    type: "Red Sword",
    typeImg: "/images/weapon-icons/red-sword.png",
    movement: "Armored",
    movementImg: "/images/movement-icons/armored.png",
    weapon: 8,
    weaponName: "Brave Sword+",
    special: "Pavise",
    skillB: "Follow-Up Ring",
    skillC: "Drive Def 2",
    spdBonus: true,
    bonusValueSpd: -5,
    hp: [60, 60, 60],
    atk: [36, 36, 36],
    spd: [16, 16, 16],
    def: [41, 41, 41],
    res: [16, 16, 16],
    hpMin: [25, 25, 25],
    atkMin: [10, 10, 10],
    spdMin: [3, 3, 3],
    defMin: [13, 13, 13],
    resMin: [3, 3, 3],
    weaponIndex: 0,
    movementIndex: 3
  },
  arthur: {
    name: "Arthur",
    epithet: "Hapless Hero",
    image: "/images/hero-portraits/arthur.png",
    type: "Green Axe",
    typeImg: "/images/weapon-icons/green-axe.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 12,
    weaponName: "Emerald Axe+",
    assist: "Swap",
    skillA: "HP +5",
    skillB: "Lancebreaker 3",
    hp: [40, 43, 46],
    atk: [29, 32, 35],
    spd: [25, 29, 32],
    def: [26, 30, 33],
    res: [21, 24, 28],
    hpMin: [18, 19, 20],
    atkMin: [7, 8, 9],
    spdMin: [6, 7, 8],
    defMin: [7, 8, 9],
    resMin: [4, 5, 6],
    weaponIndex: 2,
    movementIndex: 0
  },
  arvis: {
    name: "Arvis",
    epithet: "Emperor of Flame",
    image: "/images/hero-portraits/arvis.png",
    type: "Red Tome",
    typeImg: "/images/weapon-icons/red-tome.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 14,
    weaponName: "Valflame",
    special: "Growing Flame",
    skillB: "Recover Ring",
    skillC: "Def Ploy 3",
    hp: [33, 33, 33],
    atk: [34, 34, 34],
    spd: [31, 31, 31],
    def: [17, 17, 17],
    res: [33, 33, 33],
    hpMin: [18, 18, 18],
    atkMin: [8, 8, 8],
    spdMin: [7, 7, 7],
    defMin: [4, 4, 4],
    resMin: [7, 7, 7],
    weaponIndex: 3,
    movementIndex: 0
  },
  athena: {
    name: "Athena",
    epithet: "Borderland Sword",
    image: "/images/hero-portraits/athena.png",
    type: "Red Sword",
    typeImg: "/images/weapon-icons/red-sword.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 13,
    weaponName: "Wo Dao+",
    special: "Moonbow",
    skillA: "Sturdy Blow 2",
    skillC: "Sword Exp. 3",
    hp: [33, 36, 40],
    atk: [28, 31, 34],
    spd: [35, 38, 41],
    def: [24, 27, 28],
    res: [21, 24, 28],
    hpMin: [16, 17, 18],
    atkMin: [6, 7, 8],
    spdMin: [9, 10, 11],
    defMin: [7, 8, 9],
    resMin: [4, 5, 6],
    weaponIndex: 0,
    movementIndex: 0
  },
  ayra: {
    name: "Ayra",
    epithet: "Astra's Wielder",
    image: "/images/hero-portraits/ayra.png",
    type: "Red Sword",
    typeImg: "/images/weapon-icons/red-sword.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 16,
    weaponName: "Ayra's Blade",
    special: "Regnal Astra",
    skillA: "Swift Sparrow 2",
    skillB: "Desperation 3",
    spdBonus: true,
    bonusValueSpd: 3,
    hp: [37, 41, 44],
    atk: [30, 33, 36],
    spd: [34, 37, 40],
    def: [28, 31, 34],
    res: [18, 21, 24],
    hpMin: [18, 19, 20],
    atkMin: [6, 7, 8],
    spdMin: [10, 11, 12],
    defMin: [6, 7, 8],
    resMin: [3, 4, 5],
    weaponIndex: 0,
    movementIndex: 0
  },
  azama: {
    name: "Azama",
    epithet: "Carefree Monk",
    image: "/images/hero-portraits/azama.png",
    type: "Staff",
    typeImg: "/images/weapon-icons/staff.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 10,
    weaponName: "Pain+",
    assist: "Martyr+",
    special: "Solid-Earth Balm",
    skillC: "Threaten Atk 3",
    hp: [40, 43, 46],
    atk: [18, 21, 24],
    spd: [23, 26, 30],
    def: [29, 32, 35],
    res: [22, 25, 29],
    hpMin: [18, 19, 20],
    atkMin: [3, 4, 5],
    spdMin: [6, 7, 8],
    defMin: [7, 8, 9],
    resMin: [5, 6, 7],
    weaponIndex: 8,
    movementIndex: 0
  },
  azura: {
    name: "Azura",
    epithet: "Lady of the Lake",
    image: "/images/hero-portraits/azura.png",
    type: "Blue Lance",
    typeImg: "/images/weapon-icons/blue-lance.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 12,
    weaponName: "Sapphire Lance+",
    assist: "Sing",
    skillA: "Speed +3",
    skillC: "Fortify Res 3",
    hp: [33, 36, 40],
    atk: [28, 31, 34],
    spd: [30, 33, 36],
    def: [18, 21, 24],
    res: [24, 28, 31],
    hpMin: [16, 17, 18],
    atkMin: [4, 5, 6],
    spdMin: [6, 7, 8],
    defMin: [3, 4, 5],
    resMin: [5, 6, 7],
    weaponIndex: 1,
    movementIndex: 0
  },
  azura_ny: {
    name: "Azura",
    epithet: "Celebratory Spirit",
    image: "/images/hero-portraits/azura_ny.png",
    type: "Green Axe",
    typeImg: "/images/weapon-icons/green-axe.png",
    movement: "flying",
    movementImg: "/images/movement-icons/flying.png",
    weapon: 14,
    weaponName: "Hagoita+",
    assist: "Sing",
    skillB: "Earth Dance 3",
    skillC: "Hone Fliers",
    hp: [33, 37, 40],
    atk: [27, 30, 33],
    spd: [32, 35, 38],
    def: [19, 22, 25],
    res: [22, 26, 29],
    hpMin: [14, 15, 16],
    atkMin: [5, 6, 7],
    spdMin: [8, 9, 10],
    defMin: [4, 5, 6],
    resMin: [3, 4, 5],
    weaponIndex: 2,
    movementIndex: 2
  },
  azura_pa: {
    name: "Azura",
    epithet: "Lady of Ballads",
    image: "/images/hero-portraits/azura_pa.png",
    type: "Green Axe",
    typeImg: "/images/weapon-icons/green-axe.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 16,
    weaponName: "Urðr",
    assist: "Sing",
    skillA: "Triangle Adept 3",
    skillC: "Drive Res 2",
    hp: [32, 35, 39],
    atk: [29, 32, 35],
    spd: [31, 34, 37],
    def: [17, 20, 23],
    res: [24, 28, 31],
    hpMin: [15, 16, 17],
    atkMin: [5, 6, 7],
    spdMin: [7, 8, 9],
    defMin: [2, 3, 4],
    resMin: [5, 6, 7],
    weaponIndex: 2,
    movementIndex: 0
  },
  barst: {
    name: "Barst",
    epithet: "The Hatchet",
    image: "/images/hero-portraits/barst.png",
    type: "Green Axe",
    typeImg: "/images/weapon-icons/green-axe.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 8,
    weaponName: "Brave Axe+",
    assist: "Reposition",
    skillB: "Knock Back",
    skillC: "Spur Atk 3",
    spdBonus: true,
    bonusValueSpd: -5,
    hp: [43, 46, 49],
    atk: [30, 33, 36],
    spd: [29, 32, 35],
    def: [27, 30, 33],
    res: [13, 17, 20],
    hpMin: [19, 20, 21],
    atkMin: [8, 9, 10],
    spdMin: [7, 8, 9],
    defMin: [5, 6, 7],
    resMin: [3, 4, 5],
    weaponIndex: 2,
    movementIndex: 0
  },
  bartre: {
    name: "Bartre",
    epithet: "Fearless Warrior",
    image: "/images/hero-portraits/bartre.png",
    type: "Green-Axe",
    typeImg: "/images/weapon-icons/green-axe.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 12,
    weaponName: "Hammer+",
    assist: "Smite",
    skillA: "Fury 3",
    skillB: "Brash Assault 3",
    hp: [46, 49, 52],
    atk: [33, 36, 39],
    spd: [22, 25, 29],
    def: [30, 33, 36],
    res: [10, 13, 17],
    hpMin: [20, 21, 22],
    atkMin: [9, 10, 11],
    spdMin: [5, 6, 7],
    defMin: [6, 7, 8],
    resMin: [2, 3, 4],
    weaponIndex: 2,
    movementIndex: 0
  },
  berkut: {
    name: "Berkut",
    epithet: "Prideful Prince",
    image: "/images/hero-portraits/berkut.png",
    type: "Blue Lance",
    typeImg: "/images/weapon-icons/blue-lance.png",
    movement: "cavalry",
    movementImg: "/images/movement-icons/cavalry.png",
    weapon: 14,
    weaponName: "Berkut's Lance",
    speecial: "Blazing Flame",
    skillA: "Water Boost 3",
    skillC: "Ward Cavalry",
    hp: [43, 43, 43],
    atk: [34, 34, 34],
    spd: [22, 22, 22],
    def: [31, 31, 31],
    res: [24, 24, 24],
    hpMin: [19, 19, 19],
    atkMin: [8, 8, 8],
    spdMin: [5, 5, 5],
    defMin: [7, 7, 7],
    resMin: [7, 7, 7],
    weaponIndex: 1,
    movementIndex: 1
  },
  beruka: {
    name: "Beruka",
    epithet: "Quiet Assassin",
    image: "/images/hero-portraits/beruka.png",
    type: "Green Axe",
    typeImg: "/images/weapon-icons/green-axe.png",
    movement: "Flying",
    movementImg: "/images/movement-icons/flying.png",
    weapon: 11,
    weaponName: "Killer Axe+",
    special: "Glimmer",
    skillA: "Defiant Def 3",
    skillB: "Lunge",
    hp: [43, 46, 49],
    atk: [25, 29, 32],
    spd: [20, 23, 26],
    def: [34, 37, 40],
    res: [19, 22, 25],
    hpMin: [19, 20, 21],
    atkMin: [6, 7, 8],
    spdMin: [5, 6, 7],
    defMin: [8, 9, 10],
    resMin: [4, 5, 6],
    weaponIndex: 2,
    movementIndex: 2
  },
  blackKnight: {
    name: "Black Knight",
    epithet: "Sinister General",
    image: "/images/hero-portraits/blackKnight.png",
    type: "Red Sword",
    typeImg: "/images/weapon-icons/red-sword.png",
    movement: "armored",
    movementImg: "/images/movement-icons/armored.png",
    weapon: 16,
    weaponName: "Alondite",
    special: "Black Luna",
    skillA: "Steady Stance 3",
    skillB: "Wings of Mercy 3",
    hp: [48, 48, 48],
    atk: [34, 34, 34],
    spd: [34, 34, 34],
    def: [35, 35, 35],
    res: [18, 18, 18],
    hpMin: [22, 22, 22],
    atkMin: [10, 10, 10],
    spdMin: [8, 8, 8],
    defMin: [9, 9, 9],
    resMin: [5, 5, 5],
    weaponIndex: 0,
    movementIndex: 3
  },
  boey: {
    name: "Boey",
    epithet: "Skillful Survivor",
    image: "/images/hero-portraits/boey.png",
    type: "Green Tome",
    typeImg: "/images/weapon-icons/green-tome.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 10,
    weaponName: "Gronnowl+",
    special: "Ignis",
    skillA: "Earth Boost 3",
    skillB: "Renewal 3",
    hp: [40, 43, 46],
    atk: [25, 29, 32],
    spd: [23, 27, 30],
    def: [29, 32, 35],
    res: [14, 18, 21],
    hpMin: [18, 19, 20],
    atkMin: [6, 7, 8],
    spdMin: [4, 5, 6],
    defMin: [7, 8, 9],
    resMin: [4, 5, 6],
    weaponIndex: 5,
    movementIndex: 0
  },
  caeda: {
    name: "Caeda",
    epithet: "Talys's Heart",
    image: "/images/hero-portraits/caeda.png",
    type: "Red Sword",
    typeImg: "/images/weapon-icons/red-sword.png",
    movement: "flying",
    movementImg: "/images/movement-icons/Flying.png",
    weapon: 12,
    weaponName: "Armorslayer+",
    assist: "Rally Speed",
    skillA: "Darting Blow 3",
    skillC: "Fortify Fliers",
    hp: [33, 36, 40],
    atk: [22, 25, 29],
    spd: [34, 37, 40],
    def: [21, 24, 28],
    res: [31, 34, 37],
    hpMin: [16, 17, 18],
    atkMin: [5, 6, 7],
    spdMin: [8, 9, 10],
    defMin: [4, 5, 6],
    resMin: [9, 10, 11],
    weaponIndex: 0,
    movementIndex: 2
  },
  caeda_bb: {
    name: "Caeda",
    epithet: "Talys's Bride",
    image: "/images/hero-portraits/caeda_bb.png",
    type: "Blue Tome",
    typeImg: "/images/weapon-icons/blue-tome.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 12,
    weaponName: "Blessed Bouquet+",
    special: "Iceberg",
    skillA: "Attack/Res 2",
    skillC: "Hone Spd 3",
    hp: [30, 33, 36],
    atk: [25, 29, 32],
    spd: [34, 37, 40],
    def: [16, 19, 22],
    res: [26, 30, 33],
    hpMin: [15, 16, 17],
    atkMin: [6, 7, 8],
    spdMin: [8, 9, 10],
    defMin: [3, 4, 5],
    resMin: [7, 8, 9],
    weaponIndex: 4,
    movementIndex: 0
  },
  cain: {
    name: "Cain",
    epithet: "The Bull",
    image: "/images/hero-portraits/cain.png",
    type: "Red Sword",
    typeImg: "/images/weapon-icons/red-sword.png",
    movement: "cavalry",
    movementImg: "/images/movement-icons/cavalry.png",
    weapon: 8,
    weaponName: "Brave Sword+",
    special: "Escutcheon",
    skillB: "Wings of Mercy 3",
    skillC: "Threaten Atk 3",
    spdBonus: true,
    bonusValueSpd: -5,
    hp: [39, 42, 45],
    atk: [29, 32, 35],
    spd: [29, 32, 35],
    def: [24, 27, 31],
    res: [18, 21, 24],
    hpMin: [17, 18, 19],
    atkMin: [7, 8, 9],
    spdMin: [5, 6, 7],
    defMin: [7, 8, 9],
    resMin: [5, 6, 7],
    weaponIndex: 0,
    movementIndex: 1
  },
  camilla: {
    name: "Camilla",
    epithet: "Bewitching Beauty",
    image: "/images/hero-portraits/camilla.png",
    type: "Green Axe",
    typeImg: "/images/weapon-icons/green-axe.png",
    movement: "flying",
    movementImg: "/images/movement-icons/flying.png",
    weapon: 8,
    weaponName: "Brave Axe+",
    special: "Draconic Aura",
    skillA: "Darting Blow 3",
    skillC: "Savage Blow 3",
    spdBonus: true,
    bonusValueSpd: -5,
    hp: [34, 37, 41],
    atk: [26, 30, 33],
    spd: [29, 32, 35],
    def: [24, 28, 31],
    res: [28, 31, 34],
    hpMin: [17, 18, 19],
    atkMin: [7, 8, 9],
    spdMin: [7, 8, 9],
    defMin: [5, 6, 7],
    resMin: [6, 7, 8],
    weaponIndex: 2,
    movementIndex: 2
  },
  camilla_ny: {
    name: "Camilla",
    epithet: "Holiday Traveler",
    image: "/images/hero-portraits/camilla_ny.png",
    type: "Red Sword",
    typeImg: "/images/weapon-icons/red-sword.png",
    movement: "flying",
    movementImg: "/images/movement-icons/flying.png",
    weapon: 14,
    weaponName: "Kadomatsu+",
    special: "Draconic Aura",
    skillA: "Spd/Def Bond 3",
    skillC: "Ward Fliers",
    hp: [36, 40, 43],
    atk: [30, 33, 36],
    spd: [32, 35, 38],
    def: [28, 31, 34],
    res: [20, 23, 27],
    hpMin: [17, 18, 19],
    atkMin: [8, 9, 10],
    spdMin: [8, 9, 10],
    defMin: [6, 7, 8],
    resMin: [3, 4, 5],
    weaponIndex: 0,
    movementIndex: 2
  },
  camilla_sf: {
    name: "Camilla",
    epithet: "Spring Princess",
    image: "/images/hero-portraits/camilla_sf.png",
    type: "Green Tome",
    typeImg: "/images/weapon-icons/green-tome.png",
    movement: "flying",
    movementImg: "/images/movement-icons/flying.png",
    weapon: 11,
    weaponName: "Green Egg+",
    assist: "Rally Attack",
    skillA: "Defiant Spd 3",
    skillB: "Life for Bounty",
    hp: [35, 39, 42],
    atk: [32, 35, 38],
    spd: [22, 25, 29],
    def: [26, 30, 33],
    res: [16, 19, 22],
    hpMin: [16, 17, 18],
    atkMin: [8, 9, 10],
    spdMin: [5, 6, 7],
    defMin: [7, 8, 9],
    resMin: [3, 4, 5],
    weaponIndex: 5,
    movementIndex: 2
  },
  camus: {
    name: "Camus",
    epithet: "Sable Knight",
    image: "/images/hero-portraits/camus.png",
    type: "Blue Lance",
    typeImg: "/images/weapon-icons/blue-lance.png",
    movement: "cavalry",
    movementImg: "/images/movement-icons/cavalry.png",
    weapon: 16,
    weaponName: "Gradvius",
    special: "Growing Thunder",
    skillA: "Grani's Shield",
    skillC: "Goad Cavalry",
    hp: [42, 42, 42],
    atk: [32, 32, 32],
    spd: [33, 33, 33],
    def: [31, 31, 31],
    res: [17, 17, 17],
    hpMin: [18, 18, 18],
    atkMin: [8, 8, 8],
    spdMin: [9, 9, 9],
    defMin: [7, 7, 7],
    resMin: [4, 4, 4],
    weaponIndex: 1,
    movementIndex: 1
  },
  catria: {
    name: "Catria",
    epithet: "Middle Whitewing",
    image: "/images/hero-portraits/catria.png",
    type: "Blue Lance",
    typeImg: "/images/weapon-icons/blue-lance.png",
    movement: "flying",
    movementImg: "/images/movement-icons/flying.png",
    weapon: 11,
    weaponName: "Killer Lance+",
    special: "Luna",
    skillA: "Armored Blow 3",
    skillC: "Seal Atk 3",
    hp: [35, 39, 42],
    atk: [28, 31, 34],
    spd: [31, 34, 37],
    def: [25, 29, 32],
    res: [22, 25, 29],
    hpMin: [16, 17, 18],
    atkMin: [6, 7, 8],
    spdMin: [9, 10, 11],
    defMin: [6, 7, 8],
    resMin: [5, 6, 7],
    weaponIndex: 1,
    movementIndex: 2
  },
  cecilia: {
    name: "Cecilia",
    epithet: "Etrurian General",
    image: "/images/hero-portraits/cecilia.png",
    type: "Green Tome",
    typeImg: "/images/weapon-icons/green-tome.png",
    movement: "cavalry",
    movementImg: "/images/movement-icons/cavalry.png",
    weapon: 11,
    weaponName: "Gronnraven+",
    assist: "Rally Resistance",
    skillA: "Attack +3",
    skillB: "Escape Route 3",
    hp: [33, 36, 40],
    atk: [29, 32, 35],
    spd: [22, 25, 29],
    def: [19, 22, 25],
    res: [25, 29, 32],
    hpMin: [16, 17, 18],
    atkMin: [7, 8, 9],
    spdMin: [5, 6, 7],
    defMin: [4, 5, 6],
    resMin: [6, 7, 8],
    weaponIndex: 5,
    movementIndex: 1
  },
  celica: {
    name: "Celica",
    epithet: "Caring Princess",
    image: "/images/hero-portraits/celica.png",
    type: "Red Tome",
    typeImg: "/images/weapon-icons/red-tome.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 14,
    weaponName: "Ragnarok",
    special: "Blazing Light",
    skillA: "Distant Def 3",
    skillC: "Spur Def 3",
    hp: [35, 39, 42],
    atk: [29, 32, 35],
    spd: [30, 33, 36],
    def: [19, 22, 25],
    res: [19, 22, 25],
    hpMin: [16, 17, 18],
    atkMin: [7, 8, 9],
    spdMin: [6, 7, 8],
    defMin: [4, 5, 6],
    resMin: [6, 7, 8],
    weaponIndex: 3,
    movementIndex: 0
  },
  celica_fh: {
    name: "Celica",
    epithet: "Imprisoned Soul",
    image: "/images/hero-portraits/celica_fh.png",
    type: "Red Sword",
    typeImg: "/images/weapon-icons/red-sword.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 16,
    weaponName: "Beloved Zofia",
    special: "Luna",
    skillB: "Chill Spd 3",
    skillC: "Hone Atk 3",
    defBonus: true,
    bonusValueDef: 3,
    hp: [36, 40, 43],
    atk: [32, 35, 38],
    spd: [32, 35, 38],
    def: [23, 27, 30],
    res: [23, 26, 30],
    hpMin: [17, 18, 19],
    atkMin: [8, 9, 10],
    spdMin: [8, 9, 10],
    defMin: [4, 5, 6],
    resMin: [6, 7, 8],
    weaponIndex: 0,
    movementIndex: 0
  },
  charlotte_bb: {
    name: "Charlotte",
    epithet: "Money Maiden",
    image: "/images/hero-portraits/charlotte_bb.png",
    type: "Blue Lance",
    typeImg: "/images/weapon-icons/blue-lance.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 14,
    weaponName: "First Bite+",
    assist: "Smite",
    skillA: "Wind Boost 3",
    skillC: "Threaten Atk 3",
    hp: [43, 46, 49],
    atk: [33, 36, 39],
    spd: [29, 32, 35],
    def: [21, 24, 28],
    res: [16, 19, 22],
    hpMin: [19, 20, 21],
    atkMin: [9, 10, 11],
    spdMin: [7, 8, 9],
    defMin: [4, 5, 6],
    resMin: [3, 4, 5],
    weaponIndex: 1,
    movementIndex: 0
  },
  cherche: {
    name: "Cherche",
    epithet: "Wyvern Friend",
    image: "/images/hero-portraits/cherche.png",
    type: "Green Axe",
    typeImg: "/images/weapon-icons/green-axe.png",
    movement: "flying",
    movementImg: "/images/movement-icons/flying.png",
    weapon: 12,
    weaponName: "Hammer+",
    assist: "Pivot",
    skillA: "Attack +3",
    skillC: "Fortify Def 3",
    hp: [43, 46, 49],
    atk: [35, 38, 41],
    spd: [22, 25, 29],
    def: [29, 32, 35],
    res: [12, 16, 19],
    hpMin: [19, 20, 21],
    atkMin: [9, 10, 11],
    spdMin: [5, 6, 7],
    defMin: [7, 8, 9],
    resMin: [2, 3, 4],
    weaponIndex: 2,
    movementIndex: 2
  },
  chrom: {
    name: "Chrom",
    epithet: "Exalted Prince",
    image: "/images/hero-portraits/chrom.png",
    type: "Red Sword",
    typeImg: "/images/weapon-icons/red-sword.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 16,
    weaponName: "Falchion",
    special: "Aether",
    skillA: "Defiant Def 3",
    skillC: "Spur Def 3",
    hp: [44, 47, 50],
    atk: [34, 37, 40],
    spd: [22, 25, 29],
    def: [28, 31, 34],
    res: [13, 17, 20],
    hpMin: [20, 21, 22],
    atkMin: [8, 9, 10],
    spdMin: [5, 6, 7],
    defMin: [6, 7, 8],
    resMin: [3, 4, 5],
    weaponIndex: 0,
    movementIndex: 0
  },
  chrom_sf: {
    name: "Chrom",
    epithet: "Spring Exalt",
    image: "/images/hero-portraits/chrom_sf.png",
    type: "Green Axe",
    typeImg: "/images/weapon-icons/green-axe.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 13,
    weaponName: "Carrot Axe+",
    assist: "Shove",
    skillA: "Attack/Def +2",
    skillC: "Axe Experience 3",
    hp: [40, 43, 46],
    atk: [32, 35, 38],
    spd: [29, 32, 35],
    def: [24, 28, 31],
    res: [17, 20, 23],
    hpMin: [18, 19, 20],
    atkMin: [8, 9, 10],
    spdMin: [7, 8, 9],
    defMin: [5, 6, 7],
    resMin: [4, 5, 6],
    weaponIndex: 2,
    movementIndex: 0
  },
  chrom_bk: {
    name: "Chrom",
    epithet: "Knight Exalt",
    image: "/images/hero-portraits/chrom_bk.png",
    type: "Red Sword",
    typeImg: "/images/weapon-icons/red-sword.png",
    movement: "cavalry",
    movementImg: "/images/movement-icons/cavalry.png",
    weapon: 16,
    weaponName: "Sealed Falchion",
    special: "Aether",
    skillA: "Fury 3",
    skillB: "Chill Def 3",
    skillC: "Sword Valor 3",
    hp: [37, 41, 44],
    atk: [34, 37, 40],
    spd: [24, 28, 31],
    def: [31, 34, 37],
    res: [13, 17, 20],
    hpMin: [18, 19, 20],
    atkMin: [8, 9, 10],
    spdMin: [5, 6, 7],
    defMin: [7, 8, 9],
    resMin: [3, 4, 5],
    weaponIndex: 0,
    movementIndex: 1
  },
  chrom_we: {
    name: "Chrom",
    epithet: "Gifted Leader",
    image: "/images/hero-portraits/chrom_we.png",
    type: "Green Axe",
    typeImg: "/images/weapon-icons/green-axe.png",
    movement: "armored",
    movementImg: "/images/movement-icons/armored.png",
    weapon: 14,
    weaponName: "Sack o' Gifts+",
    assist: "Pivot",
    skillA: "Brazen Atk/Def 3",
    skillB: "Wary Fighter 3",
    hp: [48, 51, 54],
    atk: [37, 40, 43],
    spd: [16, 19, 22],
    def: [32, 35, 38],
    res: [26, 29, 32],
    hpMin: [24, 25, 26],
    atkMin: [11, 12, 13],
    spdMin: [3, 4, 5],
    defMin: [8, 9, 10],
    resMin: [4, 5, 6],
    weaponIndex: 2,
    movementIndex: 3
  },
  clair: {
    name: "Clair",
    epithet: "Highborn Flier",
    image: "/images/hero-portraits/clair.png",
    type: "Blue Lance",
    typeImg: "/images/weapon-icons/blue-lance.png",
    movement: "flying",
    movementImg: "/images/movement-icons/flying.png",
    weapon: 15,
    weaponName: "Silver Lance+",
    assist: "Harsh Command",
    skillB: "Hit and Run",
    skillC: "Spur Spd 3",
    hp: [34, 37, 41],
    atk: [23, 26, 30],
    spd: [33, 36, 39],
    def: [21, 24, 28],
    res: [30, 33, 36],
    hpMin: [17, 18, 19],
    atkMin: [6, 7, 8],
    spdMin: [7, 8, 9],
    defMin: [4, 5, 6],
    resMin: [8, 9, 10],
    weaponIndex: 1,
    movementIndex: 2
  },
  clarine: {
    name: "Clarine",
    epithet: "Refined Noble",
    image: "/images/hero-portraits/clarine.png",
    type: "Staff",
    typeImg: "/images/weapon-icons/staff.png",
    movement: "cavalry",
    movementImg: "/images/movement-icons/cavalry.png",
    weapon: 12,
    weaponName: "Fear+",
    assist: "Martyr+",
    special: "Swift-Winds Balm:",
    skillA: "Resistance +3",
    hp: [32, 35, 39],
    atk: [22, 25, 29],
    spd: [30, 33, 36],
    def: [19, 22, 25],
    res: [25, 29, 32],
    hpMin: [15, 16, 17],
    atkMin: [5, 6, 7],
    spdMin: [8, 9, 10],
    defMin: [4, 5, 6],
    resMin: [6, 7, 8],
    weaponIndex: 8,
    movementIndex: 1
  },
  clarisse: {
    name: "Clarisse",
    epithet: "Sniper in the Dark",
    image: "/images/hero-portraits/clarisse.png",
    type: "Bow",
    typeImg: "/images/weapon-icons/bow.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 11,
    weaponName: "Clarisse's Bow+",
    special: "Glimmer",
    skillB: "Poison Strike 3",
    skillC: "Threaten Def 3",
    hp: [37, 37, 37],
    atk: [31, 31, 31],
    spd: [34, 34, 34],
    def: [25, 25, 25],
    res: [20, 20, 20],
    hpMin: [18, 18, 18],
    atkMin: [7, 7, 7],
    spdMin: [8, 8, 8],
    defMin: [6, 6, 6],
    resMin: [5, 5, 5],
    weaponIndex: 6,
    movementIndex: 0
  },
  clive: {
    name: "Clive",
    epithet: "Idealisitc Knight",
    image: "/images/hero-portraits/clive.png",
    type: "Blue Lance",
    typeImg: "/images/weapon-icons/blue-lance.png",
    movement: "cavalry",
    movementImg: "/images/movement-icons/cavalry.png",
    weapon: 15,
    weaponName: "Silver Lance+",
    special: "Escutcheon",
    skillA: "Defense +3",
    skillB: "Hit and Run",
    hp: [45, 45, 45],
    atk: [33, 33, 33],
    spd: [25, 25, 25],
    def: [32, 32, 32],
    res: [19, 19, 19],
    hpMin: [19, 19, 19],
    atkMin: [9, 9, 9],
    spdMin: [6, 6, 6],
    defMin: [8, 8, 8],
    resMin: [4, 4, 4],
    weaponIndex: 1,
    movementIndex: 1
  },
  cordelia: {
    name: "Cordelia",
    epithet: "Knight Paragon",
    image: "/images/hero-portraits/cordelia.png",
    type: "Blue Lance",
    typeImg: "/images/weapon-icons/blue-lance.png",
    movement: "flying",
    movementImg: "/images/movement-icons/flying.png",
    weapon: 8,
    weaponName: "Brave Lance+",
    special: "Galeforce",
    skillA: "Triangle Adept 3",
    skillB: "Pass 3",
    spdBonus: true,
    bonusValueSpd: -5,
    hp: [36, 40, 43],
    atk: [32, 35, 38],
    spd: [32, 35, 38],
    def: [19, 22, 25],
    res: [22, 25, 29],
    hpMin: [17, 18, 19],
    atkMin: [8, 9, 10],
    spdMin: [8, 9, 10],
    defMin: [4, 5, 6],
    resMin: [5, 6, 7],
    weaponIndex: 1,
    movementIndex: 2
  },
  cordelia_bb: {
    name: "Cordelia",
    epithet: "Perfect Bride",
    image: "/images/hero-portraits/cordelia_bb.png",
    type: "Bow",
    typeImg: "/images/weapon-icons/bow.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 12,
    weaponName: "Cupid Arrow+",
    assist: "Rally Atk/Spd",
    skillB: "Escape Route 3",
    skillC: "Breath of Life 3",
    hp: [33, 36, 30],
    atk: [32, 35, 38],
    spd: [32, 35, 38],
    def: [16, 19, 22],
    res: [19, 22, 25],
    hpMin: [16, 17, 18],
    atkMin: [8, 9, 10],
    spdMin: [8, 9, 10],
    defMin: [3, 4, 5],
    resMin: [4, 5, 6],
    weaponIndex: 6,
    movementIndex: 0
  },
  corrinF: {
    name: "Corrin",
    epithet: "Fateful Princess",
    image: "/images/hero-portraits/corrinF.png",
    type: "Blue Dragonstone",
    typeImg: "/images/weapon-icons/blue-stone.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 13,
    weaponName: "Dark Breath+",
    special: "Draconic Aura",
    skillB: "Seal Res 3",
    skillC: "Hone Atk 3",
    hp: [37, 41, 44],
    atk: [24, 27, 31],
    spd: [31, 34, 37],
    def: [31, 34, 37],
    res: [18, 21, 24],
    hpMin: [18, 19, 20],
    atkMin: [7, 8, 9],
    spdMin: [5, 6, 7],
    defMin: [7, 8, 9],
    resMin: [5, 6, 7],
    weaponIndex: 9,
    movementIndex: 0
  },
  corrinF_ns: {
    name: "Corrin",
    epithet: "Novice Vacationer",
    image: "/images/hero-portraits/corrinF_ns.png",
    type: "Blue Tome",
    typeImg: "/images/weapon-icons/blue-tome.png",
    movement: "flying",
    movementImg: "/images/movement-icons/flying.png",
    weapon: 12,
    weaponName: "Sealife Tome+",
    special: "Dragon Fang",
    skillA: "Swift Strike 2",
    skillC: "Fortify Fliers",
    hp: [31, 34, 37],
    atk: [28, 31, 34],
    spd: [31, 34, 37],
    def: [19, 22, 25],
    res: [23, 26, 30],
    hpMin: [16, 17, 18],
    atkMin: [6, 7, 8],
    spdMin: [7, 8, 9],
    defMin: [4, 5, 6],
    resMin: [6, 7, 8],
    weaponIndex: 4,
    movementIndex: 2
  },
  corrinM: {
    name: "Corrin",
    epithet: "Fateful Prince",
    image: "/images/hero-portraits/corrinM.png",
    type: "Red Sword",
    typeImg: "/images/weapon-icons/red-sword.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 16,
    weaponName: "Yato",
    special: "Dragon Fang",
    skillA: "Defense +3",
    skillB: "Obstruct 3",
    hp: [38, 42, 45],
    atk: [29, 32, 35],
    spd: [29, 32, 35],
    def: [24, 28, 31],
    res: [21, 24, 28],
    hpMin: [19, 20, 21],
    atkMin: [7, 8, 9],
    spdMin: [7, 8, 9],
    defMin: [5, 6, 7],
    resMin: [4, 5, 6],
    weaponIndex: 0,
    movementIndex: 0
  },
  corrinM_ny: {
    name: "Corrin",
    epithet: "Enjoying Tradition",
    image: "/images/hero-portraits/corrinM_ny.png",
    type: "Bow",
    typeImg: "/images/weapon-icons/bow.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 12,
    weaponName: "Hama Ya+",
    assist: "Rally Def/Res",
    skillA: "Attack/Def +2",
    skillC: "Spur Def/Res +2",
    hp: [37, 37, 37],
    atk: [32, 32, 32],
    spd: [30, 30, 30],
    def: [34, 34, 34],
    res: [18, 18, 18],
    hpMin: [18, 18, 18],
    atkMin: [8, 8, 8],
    spdMin: [8, 8, 8],
    defMin: [6, 6, 6],
    resMin: [5, 5, 5],
    weaponIndex: 6,
    movementIndex: 0
  },
  deirdre: {
    name: "Deirdre",
    epithet: "Lady of the Forest",
    image: "/images/hero-portraits/deirdre.png",
    type: "Green Tome",
    typeImg: "/images/weapon-icons/green-tome.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 14,
    weaponName: "Divine Naga",
    assist: "Ardent Sacrifice",
    skillB: "Quick Riposte 3",
    skillC: "Skill Ploy 3",
    hp: [33, 36, 40],
    atk: [30, 33, 36],
    spd: [24, 28, 31],
    def: [12, 16, 19],
    res: [32, 35, 38],
    hpMin: [16, 17, 18],
    atkMin: [8, 9, 10],
    spdMin: [5, 6, 7],
    defMin: [2, 3, 4],
    resMin: [8, 9, 10],
    weaponIndex: 5,
    movementIndex: 0
  },
  delthea: {
    name: "Delthea",
    epithet: "Free Spirit",
    image: "/images/hero-portraits/delthea.png",
    type: "Blue Tome",
    typeImg: "/images/weapon-icons/blue-tome.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 14,
    weaponName: "Dark Aura",
    special: "Miracle",
    skillA: "Death Blow 3",
    skillC: "Drive Atk 2",
    hp: [30, 33, 36],
    atk: [33, 36, 39],
    spd: [31, 34, 37],
    def: [10, 13, 17],
    res: [28, 31, 34],
    hpMin: [15, 16, 17],
    atkMin: [9, 10, 11],
    spdMin: [7, 8, 9],
    defMin: [2, 3, 4],
    resMin: [6, 7, 8],
    weaponIndex: 4,
    movementIndex: 0
  },
  donnel: {
    name: "Donnel",
    epithet: "Village Hero",
    image: "/images/hero-portraits/donnel.png",
    type: "Blue Lance",
    typeImg: "/images/weapon-icons/blue-lance.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 8,
    weaponName: "Brave Lance+",
    assist: "Reciprocal Aid",
    skillA: "HP +5",
    skillB: "Drag Back",
    spdBonus: true,
    bonusValueSpd: -5,
    hp: [40, 43, 46],
    atk: [32, 35, 38],
    spd: [26, 29, 32],
    def: [29, 32, 35],
    res: [20, 23, 27],
    hpMin: [16, 17, 18],
    atkMin: [6, 7, 8],
    spdMin: [4, 5, 6],
    defMin: [5, 6, 7],
    resMin: [3, 4, 5],
    weaponIndex: 1,
    movementIndex: 0
  },
  dorcas: {
    name: "Dorcas",
    epithet: "Serene Warrior",
    image: "/images/hero-portraits/dorcas.png",
    type: "Green Axe",
    typeImg: "/images/weapon-icons/green-axe.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 16,
    weaponName: "Stout Tomahawk",
    special: "Draconic Aura",
    skillA: "Fierce Stance 3",
    skillB: "Quick Riposte 3",
    skillC: "Infantry Pulse 3",
    hp: [42, 45, 48],
    atk: [32, 35, 38],
    spd: [20, 23, 26],
    def: [32, 35, 38],
    res: [21, 24, 28],
    hpMin: [18, 19, 20],
    atkMin: [8, 9, 10],
    spdMin: [5, 6, 7],
    defMin: [8, 9, 10],
    resMin: [4, 5, 6],
    weaponIndex: 2,
    movementIndex: 0
  },
  draug: {
    name: "Draug",
    epithet: "Gentle Giant",
    image: "/images/hero-portraits/draug.png",
    type: "Red Sword",
    typeImg: "/images/weapon-icons/red-sword.png",
    movement: "armored",
    movementImg: "/images/movement-icons/armored.png",
    weapon: 8,
    weaponName: "Brave Sword+",
    special: "Pavise",
    skillB: "Lunge",
    skillC: "Ward Armor",
    spdBonus: true,
    bonusValueSpd: -5,
    hp: [47, 50, 53],
    atk: [26, 30, 33],
    spd: [29, 32, 35],
    def: [36, 39, 42],
    res: [15, 18, 21],
    hpMin: [23, 24, 25],
    atkMin: [7, 8, 9],
    spdMin: [5, 6, 7],
    defMin: [12, 13, 14],
    resMin: [2, 3, 4],
    weaponIndex: 0,
    movementIndex: 3
  },
  effie: {
    name: "Effie",
    epithet: "Army of One",
    image: "/images/hero-portraits/effie.png",
    type: "Blue Lance",
    typeImg: "/images/weapon-icons/blue-lance.png",
    movement: "armored",
    movementImg: "/images/movement-icons/armored.png",
    weapon: 15,
    weaponName: "Silver Lance+",
    assist: "Smite",
    skillA: "Death Blow 3",
    skillB: "Wary Fighter 3",
    hp: [47, 50, 53],
    atk: [37, 40, 43],
    spd: [19, 22, 25],
    def: [29, 33, 36],
    res: [20, 23, 27],
    hpMin: [21, 22, 23],
    atkMin: [11, 12, 13],
    spdMin: [4, 5, 6],
    defMin: [10, 11, 12],
    resMin: [3, 4, 5],
    weaponIndex: 1,
    movementIndex: 3
  },
  eirika: {
    name: "Eirika",
    epithet: "Restoration Lady",
    image: "/images/hero-portraits/eirika.png",
    type: "Red Sword",
    typeImg: "/images/weapon-icons/red-sword.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 16,
    weaponName: "Sieglinde",
    assist: "Pivot",
    skillB: "Drag Back",
    skillC: "Hone Spd 3",
    hp: [39, 42, 45],
    atk: [23, 26, 30],
    spd: [32, 35, 38],
    def: [23, 26, 30],
    res: [24, 28, 31],
    hpMin: [17, 18, 19],
    atkMin: [6, 7, 8],
    spdMin: [8, 9, 10],
    defMin: [6, 7, 8],
    resMin: [5, 6, 7],
    weaponIndex: 0,
    movementIndex: 0
  },
  eirika_sm: {
    name: "Eirika",
    epithet: "Anamnesis Lady",
    image: "/images/hero-portraits/eirika_sm.png",
    type: "Red Tome",
    typeImg: "/images/weapon-icons/red-tome.png",
    movement: "cavalry",
    movementImg: "/images/movement-icons/cavalry.png",
    weapon: 14,
    weaponName: "Gleipnir",
    assist: "Rally Atk/Spd",
    skillA: "Swift Sparrow 2",
    skillB: "Desperation 3",
    skillC: "R Tome Exp. 3",
    resBonus: true,
    bonusValueRes: 3,
    hp: [33, 36, 40],
    atk: [28, 31, 34],
    spd: [32, 35, 38],
    def: [17, 20, 23],
    res: [19, 22, 25],
    hpMin: [16, 17, 18],
    atkMin: [6, 7, 8],
    spdMin: [8, 9, 10],
    defMin: [4, 5, 6],
    resMin: [4, 5, 6],
    weaponIndex: 3,
    movementIndex: 1
  },
  eldigan: {
    name: "Eldigan",
    epithet: "Lionheart",
    image: "/images/hero-portraits/eldigan.png",
    type: "Red Sword",
    typeImg: "/images/weapon-icons/red-sword.png",
    movement: "cavalry",
    movementImg: "/images/movement-icons/cavalry.png",
    weapon: 16,
    weaponName: "Mystletainn",
    special: "Growing Light",
    skillA: "Fury 3",
    skillB: "Lunge",
    hp: [42, 45, 48],
    atk: [29, 32, 35],
    spd: [21, 24, 28],
    def: [31, 34, 37],
    res: [15, 19, 22],
    hpMin: [18, 19, 20],
    atkMin: [7, 8, 9],
    spdMin: [4, 5, 6],
    defMin: [7, 8, 9],
    resMin: [5, 6, 7],
    weaponIndex: 0,
    movementIndex: 1
  },
  elincia: {
    name: "Elincia",
    epithet: "Lost Princess",
    image: "/images/hero-portraits/elincia.png",
    type: "Red Sword",
    typeImg: "/images/weapon-icons/red-sword.png",
    movement: "flying",
    movementImg: "/images/movement-icons/flying.png",
    weapon: 11,
    weaponName: "Amiti",
    assist: "Ardent Sacrifice",
    skillA: "Death Blow 3",
    skillB: "Flier Formation 3",
    spdBonus: true,
    bonusValueSpd: -2,
    hp: [32, 35, 39],
    atk: [31, 34, 37],
    spd: [33, 36, 39],
    def: [21, 24, 28],
    res: [24, 27, 31],
    hpMin: [15, 16, 17],
    atkMin: [7, 8, 9],
    spdMin: [9, 10, 11],
    defMin: [4, 5, 6],
    resMin: [7, 8, 9],
    weaponIndex: 0,
    movementIndex: 2
  },
  elise: {
    name: "Elise",
    epithet: "Budding Flower",
    image: "/images/hero-portraits/elise.png",
    type: "Staff",
    typeImg: "/images/weapon-icons/staff.png",
    movement: "cavalry",
    movementImg: "/images/movement-icons/cavalry.png",
    weapon: 10,
    weaponName: "Gravity+",
    assist: "Recover+",
    special: "Kindled-Fire Balm",
    skillB: "Live to Serve 3",
    hp: [27, 30, 33],
    atk: [29, 32, 35],
    spd: [28, 32, 35],
    def: [16, 19, 22],
    res: [29, 32, 35],
    hpMin: [14, 15, 16],
    atkMin: [7, 8, 9],
    spdMin: [7, 8, 9],
    defMin: [3, 4, 5],
    resMin: [7, 8, 9],
    weaponIndex: 8,
    movementIndex: 1
  },
  elise_ns: {
    name: "Elise",
    epithet: "Tropical Flower",
    image: "/images/hero-portraits/elise_ns.png",
    type: "Green Tome",
    typeImg: "/images/weapon-icons/green-tome.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 12,
    weaponName: "Hibiscus Tome+",
    assist: "Rally Atk/Res",
    skillA: "Spd/Res 2",
    skillC: "G Tome Valor 3",
    hp: [31, 34, 37],
    atk: [33, 36, 39],
    spd: [31, 34, 37],
    def: [15, 18, 21],
    res: [22, 25, 29],
    hpMin: [16, 17, 18],
    atkMin: [9, 10, 11],
    spdMin: [7, 8, 9],
    defMin: [2, 3, 4],
    resMin: [5, 6, 7],
    weaponIndex: 5,
    movementIndex: 0
  },
  eliwood: {
    name: "Eliwood",
    epithet: "Knight of Lycia",
    image: "/images/hero-portraits/eliwood.png",
    type: "Red Sword",
    typeImg: "/images/weapon-icons/red-sword.png",
    movement: "cavalry",
    movementImg: "/images/movement-icons/cavalry.png",
    weapon: 16,
    weaponName: "Durandal",
    special: "Sacred Cowl",
    skillB: "Axebreaker 3",
    skillC: "Ward Cavalry",
    hp: [35, 39, 42],
    atk: [28, 31, 34],
    spd: [26, 30, 33],
    def: [20, 23, 26],
    res: [29, 32, 35],
    hpMin: [16, 17, 18],
    atkMin: [6, 7, 8],
    spdMin: [7, 8, 9],
    defMin: [5, 6, 7],
    resMin: [7, 8, 9],
    weaponIndex: 0,
    movementIndex: 1
  },
  eliwood_la: {
    name: "Eliwood",
    epithet: "Devoted Love",
    image: "/images/hero-portraits/eliwood_la.png",
    type: "Blue Lance",
    typeImg: "/images/weapon-icons/blue-lance.png",
    movement: "armored",
    movementImg: "/images/movement-icons/armored.png",
    weapon: 14,
    weaponName: "Case Blanca+",
    assist: "Rally Atk/Def",
    skillA: "Fire Boost 3",
    skillC: "Goad Armor",
    hp: [47, 47, 47],
    atk: [38, 38, 38],
    spd: [32, 32, 32],
    def: [29, 29, 29],
    res: [29, 29, 29],
    hpMin: [23, 23, 23],
    atkMin: [10, 10, 10],
    spdMin: [8, 8, 8],
    defMin: [7, 7, 7],
    resMin: [7, 7, 7],
    weaponIndex: 1,
    movementIndex: 3
  },
  eprhaim: {
    name: "Ephraim",
    epithet: "Restoration Lord",
    image: "/images/hero-portraits/ephraim.png",
    type: "Blue Lance",
    typeImg: "/images/weapon-icons/blue-lance.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 16,
    weaponName: "Siegmund",
    special: "Moonbow",
    skillB: "Seal Def 3",
    skillC: "Threaten Def 3",
    hp: [42, 45, 48],
    atk: [32, 35, 38],
    spd: [22, 25, 29],
    def: [29, 32, 35],
    res: [17, 20, 23],
    hpMin: [18, 19, 20],
    atkMin: [8, 9, 10],
    spdMin: [5, 6, 7],
    defMin: [7, 8, 9],
    resMin: [4, 5, 6],
    weaponIndex: 1,
    movementIndex: 0
  },
  ephraim_l: {
    name: "Ephraim",
    epithet: "Legendary Lord",
    image: "/images/hero-portraits/ephraim_l.png",
    type: "Blue Lance",
    typeImg: "/images/weapon-icons/blue-lance.png",
    movement: "cavalry",
    movementImg: "/images/movement-icons/cavalry.png",
    weapon: 16,
    weaponName: "Flame Siegmund",
    special: "Sol",
    skillA: "Sturdy Stance 2",
    skillB: "Solar Brace",
    skillC: "Fortify Def 3",
    atkBonus: true,
    bonusValueAtk: 3,
    hp: [40, 43, 46],
    atk: [33, 36, 39],
    spd: [23, 27, 30],
    def: [30, 33, 36],
    res: [15, 18, 21],
    hpMin: [18, 19, 20],
    atkMin: [9, 10, 11],
    spdMin: [4, 5, 6],
    defMin: [8, 9, 10],
    resMin: [2, 3, 4],
    weaponIndex: 1,
    movementIndex: 1
  },
  est: {
    name: "Est",
    epithet: "Junior Whitewing",
    image: "/images/hero-portraits/est.png",
    type: "Blue Lance",
    typeImg: "/images/weapon-icons/blue-lance.png",
    movement: "flying",
    movementImg: "/images/movement-icons/flying.png",
    weapon: 12,
    weaponName: "Heavy Spear+",
    assist: "Shove",
    skillA: "Defiant Res 3",
    skillB: "Seal Spd 3",
    hp: [33, 36, 40],
    atk: [32, 35, 38],
    spd: [26, 30, 33],
    def: [21, 24, 28],
    res: [29, 32, 35],
    hpMin: [16, 17, 18],
    atkMin: [8, 9, 10],
    spdMin: [7, 8, 9],
    defMin: [4, 5, 6],
    resMin: [7, 8, 9],
    weaponIndex: 1,
    movementIndex: 2
  },
  fae: {
    name: "Fae",
    epithet: "Divine Dragon",
    image: "/images/hero-portraits/fae.png",
    type: "Green Dragonstone",
    typeImg: "/images/weapon-icons/green-stone.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 13,
    weaponName: "Light Breath+",
    assist: "Draw Back",
    skillB: "Renewal 3",
    skillC: "Threaten Atk 3",
    hp: [43, 46, 50],
    atk: [30, 33, 36],
    spd: [25, 28, 31],
    def: [22, 25, 29],
    res: [26, 30, 33],
    hpMin: [15, 16, 17],
    atkMin: [4, 5, 6],
    spdMin: [3, 4, 5],
    defMin: [5, 6, 7],
    resMin: [7, 8, 9],
    weaponIndex: 9,
    movementIndex: 0
  },
  faye: {
    name: "Faye",
    epithet: "Devoted Heart",
    image: "/images/hero-portraits/faye.png",
    type: "Bow",
    typeImg: "/images/weapon-icons/bow.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 11,
    weaponName: "Firesweep Bow+",
    special: "Noontime",
    skillB: "Wings of Mercy 3",
    skillC: "Bow Exp. 3",
    hp: [39, 42, 45],
    atk: [27, 30, 33],
    spd: [21, 25, 28],
    def: [22, 26, 29],
    res: [28, 31, 34],
    hpMin: [15, 16, 17],
    atkMin: [5, 6, 7],
    spdMin: [2, 3, 4],
    defMin: [3, 4, 5],
    resMin: [6, 7, 8],
    weaponIndex: 6,
    movementIndex: 0
  },
  felicia: {
    name: "Felicia",
    epithet: "Maid Mayhem",
    image: "/images/hero-portraits/felicia.png",
    type: "Dagger",
    typeImg: "/images/weapon-icons/dagger.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 10,
    weaponName: "Silver Dagger+",
    special: "Glacies",
    skillA: "Resistance +3",
    skillC: "Breath of Life 3",
    hp: [31, 34, 38],
    atk: [20, 23, 26],
    spd: [34, 37, 40],
    def: [15, 18, 21],
    res: [32, 35, 38],
    hpMin: [14, 15, 16],
    atkMin: [5, 6, 7],
    spdMin: [10, 11, 12],
    defMin: [2, 3, 4],
    resMin: [8, 9, 10],
    weaponIndex: 7,
    movementIndex: 0
  },
  fir: {
    name: "Fir",
    epithet: "Sword Student",
    image: "/images/hero-portraits/fir.png",
    type: "Red Sword",
    typeImg: "/images/weapon-icons/red-sword.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 11,
    weaponName: "Killing Edge+",
    special: "Glacies",
    skillA: "Speed +3",
    skillB: "Pass 3",
    hp: [37, 41, 44],
    atk: [22, 25, 29],
    spd: [33, 36, 39],
    def: [21, 24, 28],
    res: [28, 31, 34],
    hpMin: [18, 19, 20],
    atkMin: [5, 6, 7],
    spdMin: [9, 10, 11],
    defMin: [4, 5, 6],
    resMin: [6, 7, 8],
    weaponIndex: 0,
    movementIndex: 0
  },
  fjorm: {
    name: "Fjorm",
    epithet: "Princess of Ice",
    image: "/images/hero-portraits/fjorm.png",
    type: "Blue Lance",
    typeImg: "/images/weapon-icons/blue-lance.png",
    movement: "Infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 16,
    weaponName: "Leiptr",
    special: "Ice Mirror",
    skillA: "Atk/Def Bond 3",
    skillB: "Shield Pulse 3",
    skillC: "Drive Atk 2",
    hp: [35, 39, 42],
    atk: [26, 30, 33],
    spd: [28, 31, 34],
    def: [26, 30, 33],
    res: [31, 34, 37],
    hpMin: [16, 17, 18],
    atkMin: [7, 8, 9],
    spdMin: [6, 7, 8],
    defMin: [7, 8, 9],
    resMin: [7, 8, 9],
    weaponIndex: 1,
    movementIndex: 0
  },
  florina: {
    name: "Florina",
    epithet: "Lovely Flier",
    image: "/images/hero-portraits/florina.png",
    type: "Blue Lance",
    typeImg: "/images/weapon-icons/blue-lance.png",
    movement: "flying",
    movementImg: "/images/movement-icons/flying.png",
    weapon: 12,
    weaponName: "Heavy Spear+",
    assist: "Ardent Sacrifice",
    skillA: "Darting Blow 3",
    skillC: "Breath of Life 3",
    hp: [39, 42, 45],
    atk: [25, 29, 32],
    spd: [24, 27, 31],
    def: [22, 25, 29],
    res: [31, 34, 37],
    hpMin:[17, 18, 19],
    atkMin:[6, 7, 8],
    spdMin:[7, 8, 9],
    defMin:[5, 6, 7],
    resMin:[7, 8, 9],
    weaponIndex: 1,
    movementIndex: 2
  },
  frederick: {
    name: "Frederick",
    epithet: "Polite Knight",
    image: "/images/hero-portraits/frederick.png",
    type: "Green Axe",
    typeImg: "/images/weapon-icons/green-axe.png",
    movement: "cavalry",
    movementImg: "/images/movement-icons/cavalry.png",
    weapon: 12,
    weaponName: "Hammer+",
    special: "Luna",
    skillB: "Wings of Mercy 3",
    skillC: "Fortify Def 3",
    hp: [40, 43, 46],
    atk: [32, 35, 38],
    spd: [22, 25, 29],
    def: [33, 36, 39],
    res: [11, 14, 18],
    hpMin: [18, 19, 20],
    atkMin: [8, 9, 10],
    spdMin: [4, 5, 6],
    defMin: [7, 8, 9],
    resMin: [3, 4, 5],
    weaponIndex: 2,
    movementIndex: 1
  },
  frederick_ys: {
    name: "Frederick",
    epithet: "Horizon Watcher",
    image: "/images/hero-portraits/frederick_ys.png",
    type: "Dagger",
    typeImg: "/images/weapon-icons/dagger.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 10,
    weaponName: "Seashell+",
    assist: "Ardent Sacrifice",
    skillA: "Armored Blow 1",
    skillB: "Seal Atk/Spd 2",
    hp: [36, 40, 43],
    atk: [29, 32, 35],
    spd: [28, 31, 34],
    def: [24, 28, 31],
    res: [14, 18, 21],
    hpMin: [17, 18, 19],
    atkMin: [7, 8, 9],
    spdMin: [6, 7, 8],
    defMin: [5, 6, 7],
    resMin: [4, 5, 6],
    weaponIndex: 7,
    movementIndex: 0
  },
  gaius: {
    name: "Gaius",
    epithet: "Candy Stealer",
    image: "/images/hero-portraits/gaius.png",
    type: "Dagger",
    typeImg: "/images/weapon-icons/dagger.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 7,
    weaponName: "Rogue Dagger+",
    assist: "Rally Speed",
    skillA: "Defiant Atk 3",
    skillB: "Pass 3",
    hp: [39, 42, 45],
    atk: [25, 29, 32],
    spd: [33, 36, 39],
    def: [19, 22, 25],
    res: [16, 19, 22],
    hpMin: [17, 18, 19],
    atkMin: [6, 7, 8],
    spdMin: [9, 10, 11],
    defMin: [4, 5, 6],
    resMin: [3, 4, 5],
    weaponIndex: 7,
    movementIndex: 0
  },
  gaius_ys: {
    name: "Gaius",
    epithet: "Thief Exposed",
    image: "/images/hero-portraits/gaius_ys.png",
    type: "Bow",
    typeImg: "/images/weapon-icons/bow.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 12,
    weaponName: "Refreshing Bolt+",
    specials: "Astra",
    skillB: "Vantage 3",
    skillC: "Def Ploy 3",
    hp: [31, 34, 37],
    atk: [26, 30, 33],
    spd: [34, 37, 40],
    def: [16, 19, 22],
    res: [24, 28, 31],
    hpMin: [16, 17, 18],
    atkMin: [7, 8, 9],
    spdMin: [8, 9, 10],
    defMin: [3, 4, 5],
    resMin: [5, 6, 7],
    weaponIndex: 6,
    movementIndex: 0
  },
  genny: {
    name: "Genny",
    epithet: "Endearing Ally",
    image: "/images/hero-portraits/genny.png",
    type: "Staff",
    typeImg: "/images/weapon-icons/staff.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 10,
    weaponName: "Gravity+",
    assist: "Physic+",
    special: "Heavenly Light",
    skillB: "Wrathful Staff 3",
    hp: [29, 32, 35],
    atk: [32, 35, 38],
    spd: [22, 25, 29],
    def: [18, 21, 24],
    res: [31, 34, 37],
    hpMin: [16, 17, 18],
    atkMin: [8, 9, 10],
    spdMin: [5, 6, 7],
    defMin: [3, 4, 5],
    resMin: [7, 8, 9],
    weaponIndex: 8,
    movementIndex: 0
  },
  gerome: {
    name: "Gerome",
    epithet: "Masked Rider",
    image: "/images/hero-portraits/gerome.png",
    type: "Green Axe",
    typeImg: "/images/weapon-icons/green-axe.png",
    movement: "Flying",
    movementImg: "/images/movement-icons/flying.png",
    weapon: 14,
    weaponName: "Poleaxe+",
    assist: "Rally Atk/Def",
    skillA: "Fortress Def 3",
    skillB: "Hit and Run",
    hp: [45, 45, 45],
    atk: [38, 38, 38],
    spd: [25, 25, 25],
    def: [34, 34, 34],
    res: [19, 19, 19],
    hpMin: [19, 19, 19],
    atkMin: [10, 10, 10],
    spdMin: [6, 6, 6],
    defMin: [8, 8, 8],
    resMin: [4, 4, 4],
    weaponIndex: 2,
    movementIndex: 2
  },
  gordin: {
    name: "Gordin",
    epithet: "Altean Archer",
    image: "/images/hero-portraits/gordin.png",
    type: "Bow",
    typeImg: "/images/weapon-icons/bow.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 8,
    weaponName: "Brave Bow+",
    assist: "Shove",
    skillA: "Attack +3",
    skillB: "Vantage 3",
    spdBonus: true,
    bonusValueSpd: -5,
    hp: [40, 43, 46],
    atk: [28, 31, 34],
    spd: [22, 25, 29],
    def: [29, 32, 35],
    res: [13, 17, 20],
    hpMin:[18, 19, 20],
    atkMin:[6, 7, 8],
    spdMin:[5, 6, 7],
    defMin:[7, 8, 9],
    resMin:[3, 4, 5],
    weaponIndex: 6,
    movementIndex: 0
  },
  gray: {
    name: "Gray",
    epithet: "Wry Comrade",
    image: "/images/hero-portraits/gray.png",
    type: "Red Sword",
    typeImg: "/images/weapon-icons/red-sword.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 14,
    weaponName: "Zanbato+",
    assist: "Swap",
    skillA: "Wind Boost 3",
    skillC: "Sword Valor 3",
    hp: [40, 43, 46],
    atk: [32, 35, 38],
    spd: [29, 32, 35],
    def: [27, 30, 33],
    res: [19, 22, 26],
    hpMin:[16, 17, 18],
    atkMin:[6, 7, 8],
    spdMin:[5, 6, 7],
    defMin:[5, 6, 7],
    resMin:[2, 3, 4],
    weaponIndex: 0,
    movementIndex: 0
  },
  gunnthra: {
    name: "Gunnthrá",
    epithet: "Voice of Dreams",
    image: "/images/hero-portraits/gunnthrá.png",
    type: "Green Tome",
    typeImg: "/images/weapon-icons/green-tome.png",
    movement: "cavalry",
    movementImg: "/images/movement-icons/cavalry.png",
    weapon: 14,
    weaponName: "Blizzard",
    special: "Glacies",
    skillA: "Fortress Res 3",
    skillB: "Chilling Seal",
    skillC: "Res Ploy 3",
    resBonus: true,
    bonusValueRes: 3,
    hp: [33, 37, 40],
    atk: [28, 31, 34],
    spd: [30, 33, 36],
    def: [15, 19, 22],
    res: [22, 25, 29],
    hpMin:[14, 15, 16],
    atkMin:[6, 7, 8],
    spdMin:[8, 9, 10],
    defMin:[5, 6, 7],
    resMin:[5, 6, 7],
    weaponIndex: 5,
    movementIndex: 1
  },
  gunter: {
    name: "Gunter",
    epithet: "Inveterate Soldier",
    image: "/images/hero-portraits/gunter.png",
    type: "Green Axe",
    typeImg: "/images/weapon-icons/green-axe.png",
    movement: "cavalry",
    movementImg: "/images/movement-icons/cavalry.png",
    weapon: 15,
    weaponName: "Silver Axe+",
    assist: "Harsh Command",
    skillA: "Armored Blow 3",
    skillC: "Hone Cavalry",
    hp: [39, 43, 46],
    atk: [28, 32, 35],
    spd: [21, 24, 27],
    def: [39, 33, 36],
    res: [14, 18, 21],
    hpMin:[20, 21, 22],
    atkMin:[9, 10, 11],
    spdMin:[6, 7, 8],
    defMin:[10, 11, 12],
    resMin:[4, 5, 6],
    weaponIndex: 2,
    movementIndex: 1
  },
  gwendolyn: {
    name: "Gwendolyn",
    epithet: "Adorable Knight",
    image: "/images/hero-portraits/gwendolyn.png",
    type: "Blue Lance",
    typeImg: "/images/weapon-icons/blue-lance.png",
    movement: "armored",
    movementImg: "/images/movement-icons/armored.png",
    weapon: 11,
    weaponName: "Killer Lance+",
    special: "Escutcheon",
    skillB: "Drag Back",
    skillC: "Hone Armor",
    hp: [46, 49, 52],
    atk: [26, 30, 33],
    spd: [21, 24, 28],
    def: [35, 38, 41],
    res: [24, 28, 31],
    hpMin:[22, 23, 24],
    atkMin:[7, 8, 9],
    spdMin:[4, 5, 6],
    defMin:[11, 12, 13],
    resMin:[5, 6, 7],
    weaponIndex: 1,
    movementIndex: 3
  },
  hana: {
    name: "Hana",
    epithet: "Focused Samurai",
    image: "/images/hero-portraits/hana.png",
    type: "Red Sword",
    typeImg: "/images/weapon-icons/red-sword.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 12,
    weaponName: "Armorslayer+",
    assist: "Rally Attack",
    skillA: "Life and Death 3",
    skillB: "Obstruct 3",
    hp: [34, 37, 41],
    atk: [32, 35, 38],
    spd: [33, 36, 39],
    def: [20, 23, 26],
    res: [22, 26, 29],
    hpMin:[17, 18, 19],
    atkMin:[8, 9, 10],
    spdMin:[9, 10, 11],
    defMin:[5, 6, 7],
    resMin:[3, 4, 5],
    weaponIndex: 0,
    movementIndex: 0
  },
  hardin_fh: {
    name: "Hardin",
    epithet: "Dark Emperor",
    image: "/images/hero-portraits/hardin_fh.png",
    type: "Blue Lance",
    typeImg: "/images/weapon-icons/blue-lance.png",
    movement: "armored",
    movementImg: "/images/movement-icons/armored.png",
    weapon: 16,
    weaponName: "Gradvius",
    special: "Vengeance",
    skillA: "Brazen Def/Res 3",
    skillB: "Bold Fighter 3",
    hp: [41, 45, 48],
    atk: [31, 34, 37],
    spd: [24, 28, 31],
    def: [33, 36, 39],
    res: [29, 32, 35],
    hpMin:[22, 23, 24],
    atkMin:[7, 8, 9],
    spdMin:[5, 6, 7],
    defMin:[9, 10, 11],
    resMin:[7, 8, 9],
    weaponIndex: 1,
    movementIndex: 3
  },
  hawkeye: {
    name: "Hawkeye",
    epithet: "Desert Guardian",
    image: "/images/hero-portraits/hawkeye.png",
    type: "Green Axe",
    typeImg: "/images/weapon-icons/green-axe.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 11,
    weaponName: "Killer Axe+",
    special: "Growing Light",
    skillA: "Death Blow 3",
    skillC: "Threaten Atk 3",
    hp: [42, 45, 48],
    atk: [30, 33, 36],
    spd: [19, 22, 25],
    def: [24, 28, 31],
    res: [27, 30, 33],
    hpMin:[20, 21, 22],
    atkMin:[8, 9, 10],
    spdMin:[4, 5, 6],
    defMin:[5, 6, 7],
    resMin:[5, 6, 7],
    weaponIndex: 2,
    movementIndex: 0
  },
  hector: {
    name: "Hector",
    epithet: "General of Ostia",
    image: "/images/hero-portraits/hector.png",
    type: "Green Axe",
    typeImg: "/images/weapon-icons/green-axe.png",
    movement: "armored",
    movementImg: "/images/movement-icons/armored.png",
    weapon: 16,
    weaponName: "Armads",
    special: "Pavise",
    skillA: "Distant Counter",
    skillC: "Goad Armor",
    hp: [49, 52, 55],
    atk: [33, 36, 39],
    spd: [21, 24, 28],
    def: [34, 37, 40],
    res: [16, 19, 22],
    hpMin:[23, 24, 25],
    atkMin:[9, 10, 11],
    spdMin:[4, 5, 6],
    defMin:[10, 11, 12],
    resMin:[3, 4, 5],
    weaponIndex: 2,
    movementIndex: 3
  },
  hector_la: {
    name: "Hector",
    epithet: "Just Here to Fight",
    image: "/images/hero-portraits/hector_la.png",
    type: "Green Axe",
    typeImg: "/images/weapon-icons/green-axe.png",
    movement: "armored",
    movementImg: "/images/movement-icons/armored.png",
    weapon: 16,
    weaponName: "Berserk Armads",
    special: "Glimmer",
    skillA: "Distant Counter",
    skillB: "Wary Fighter 3",
    hp: [47, 50, 53],
    atk: [35, 38, 42],
    spd: [18, 21, 24],
    def: [37, 40, 43],
    res: [21, 24, 27],
    hpMin:[23, 24, 25],
    atkMin:[7, 8, 9],
    spdMin:[3, 4, 5],
    defMin:[11, 12, 13],
    resMin:[6, 7, 8],
    weaponIndex: 2,
    movementIndex: 3
  },
  henry: {
    name: "Henry",
    epithet: "Twisted Mind",
    image: "/images/hero-portraits/henry.png",
    type: "Red Tome",
    typeImg: "/images/weapon-icons/red-tome.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 11,
    weaponName: "Rauðrraven+",
    special: "Ignis",
    skillA: "Defiant Def 3",
    skillB: "G Tomebreaker 3",
    hp: [42, 45, 48],
    atk: [20, 23, 26],
    spd: [19, 22, 25],
    def: [29, 32, 35],
    res: [22, 25, 29],
    hpMin:[18, 19, 20],
    atkMin:[5, 6, 7],
    spdMin:[4, 5, 6],
    defMin:[7, 8, 9],
    resMin:[5, 6, 7],
    weaponIndex: 3,
    movementIndex: 0 
  },
  henry_hw: {
    name: "Henry",
    epithet: "Happy Vampire",
    image: "/images/hero-portraits/henry_hw.png",
    type: "Green Tome",
    typeImg: "/images/weapon-icons/green-tome.png",
    movement: "armored",
    movementImg: "/images/movement-icons/armored.png",
    weapon: 12,
    weaponName: "Spectral Tome+",
    special: "Reprisal",
    skillB: "Live for Honor",
    skillC: "Armor March 3",
    hp: [33, 36, 40],
    atk: [30, 33, 36],
    spd: [31, 34, 37],
    def: [22, 26, 29],
    res: [33, 36, 39],
    hpMin:[16, 17, 18],
    atkMin:[8, 9, 10],
    spdMin:[9, 10, 11],
    defMin:[3, 4, 5],
    resMin:[11, 12, 13],
    weaponIndex: 5,
    movementIndex: 3
  },
  hinata: {
    name: "Hinata",
    epithet: "Wild Samurai",
    image: "/images/hero-portraits/hinata.png",
    type: "Red Sword",
    typeImg: "/images/weapon-icons/red-sword.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 12,
    weaponName: "Ruby Sword+",
    special: "Pavise",
    skillA: "Fury 3",
    skillB: "Brash Assault 3",
    hp: [44, 47, 50],
    atk: [29, 32, 35],
    spd: [21, 24, 28],
    def: [33, 36, 39],
    res: [15, 18, 21],
    hpMin:[20, 21, 22],
    atkMin:[7, 8, 9],
    spdMin:[4, 5, 6],
    defMin:[9, 10, 11],
    resMin:[2, 3, 4],
    weaponIndex: 0,
    movementIndex: 0
  },
  hinoka: {
    name: "Hinoka",
    epithet: "Warrior Princess",
    image: "/images/hero-portraits/hinoka.png",
    type: "Blue Lance",
    typeImg: "/images/weapon-icons/blue-lance.png",
    movement: "flying",
    movementImg: "/images/movement-icons/flying.png",
    weapon: 8,
    weaponName: "Brave Lance+",
    special: "Blazing Wind",
    skillA: "Defiant Def 3",
    skillC: "Hone Fliers 3",
    spdBonus: true,
    bonusValueSpd: -5,
    hp: [37, 41, 44],
    atk: [32, 35, 38],
    spd: [29, 32, 35],
    def: [22, 25, 29],
    res: [21, 24, 27],
    hpMin:[18, 19, 20],
    atkMin:[6, 7, 8],
    spdMin:[7, 8, 9],
    defMin:[5, 6, 7],
    resMin:[6, 7, 8],
    weaponIndex: 1,
    movementIndex: 2
  },
  ike: {
    name: "Ike",
    epithet: "Young Mercenary",
    image: "/images/hero-portraits/ike.png",
    type: "Red Sword",
    typeImg: "/images/weapon-icons/red-sword.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 16,
    weaponName: "Ragnell",
    special: "Aether",
    skillA: "Heavy Blade 3",
    skillB: "Swordbreaker 3",
    hp: [39, 42, 45],
    atk: [32, 35, 38],
    spd: [28, 31, 34],
    def: [29, 32, 35],
    res: [14, 18, 21],
    hpMin:[17, 18, 19],
    atkMin:[8, 9, 10],
    spdMin:[6, 7, 8],
    defMin:[7, 8, 9],
    resMin:[4, 5, 6],
    weaponIndex: 0,
    movementIndex: 0
  },
  ike_bh: {
    name: "Ike",
    epithet: "Brave Mercenary",
    image: "/images/hero-portraits/ike_bh.png",
    type: "Green Axe",
    typeImg: "/images/weapon-icons/green-axe.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 16,
    weaponName: "Urvan",
    special: "Aether",
    skillA: "Steady Breath",
    skillB: "Beorc's Blessing",
    skillC: "Threaten Def 3",
    hp: [40, 43, 46],
    atk: [33, 36, 39],
    spd: [24, 28, 31],
    def: [32, 35, 38],
    res: [17, 20, 23],
    hpMin:[16, 17, 18],
    atkMin:[9, 10, 11],
    spdMin:[5, 6, 7],
    defMin:[8, 9, 10],
    resMin:[4, 5, 6],
    weaponIndex: 2,
    movementIndex: 0
  },
  ike_l: {
    name: "Ike",
    epithet: "Vanguard Legend",
    image: "/images/hero-portraits/ike_l.png",
    type: "Red Sword",
    typeImg: "/images/weapon-icons/red-sword.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 16,
    weaponName: "Ragnell",
    special: "Radiant Aether",
    skillA: "Warding Breath",
    skillB: "Seal Atk/Def 2",
    skillC: "Def Tactic 3",
    hp: [37, 41, 44],
    atk: [33, 36, 39],
    spd: [27, 30, 33],
    def: [32, 35, 38],
    res: [18, 21, 24],
    hpMin:[18, 19, 20],
    atkMin:[9, 10, 11],
    spdMin:[5, 6, 7],
    defMin:[8, 9, 10],
    resMin:[3, 4, 5],
    weaponIndex: 0,
    movementIndex: 0
  },
  inigo_pa: {
    name: "Inigo",
    epithet: "Indigo Dancer",
    image: "/images/hero-portraits/inigo_pa.png",
    type: "Green Tome",
    typeImg: "/images/weapon-icons/green-tome.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 12,
    weaponName: "Dancer's Ring+",
    assist: "Dance",
    skillB: "Gale Dance 3",
    skillC: "Hone Atk 3",
    hp: [33, 37, 40],
    atk: [24, 28, 31],
    spd: [30, 33, 36],
    def: [19, 22, 25],
    res: [17, 20, 23],
    hpMin:[14, 15, 16],
    atkMin:[5, 6, 7],
    spdMin:[6, 7, 8],
    defMin:[4, 5, 6],
    resMin:[2, 3, 4],
    weaponIndex: 5,
    movementIndex: 0
  },
  innes: {
    name: "Innes",
    epithet: "Regal Strategician",
    image: "/images/hero-portraits/innes.png",
    type: "Bow",
    typeImg: "/images/weapon-icons/bow.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 14,
    weaponName: "Nidhogg",
    special: "Iceberg",
    skillA: "Fortress Res 3",
    skillB: "Cancel Affinity 3",
    hp: [32, 35, 39],
    atk: [30, 33, 36],
    spd: [31, 34, 37],
    def: [11, 14, 18],
    res: [28, 31, 34],
    hpMin:[15, 16, 17],
    atkMin:[8, 9, 10],
    spdMin:[7, 8, 9],
    defMin:[3, 4, 5],
    resMin:[6, 7, 8],
    weaponIndex: 6,
    movementIndex: 0
  },
  jaffar: {
    name: "Jaffar",
    epithet: "Angel of Death",
    image: "/images/hero-portraits/jaffar.png",
    type: "Dagger",
    typeImg: "/images/weapon-icons/dagger.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 11,
    weaponName: "Deathly Dagger",
    special: "Glimmer",
    skillA: "Life and Death 3",
    skillC: "Threaten Spd 3",
    hp: [38, 41, 44],
    atk: [23, 26, 30],
    spd: [30, 33, 36],
    def: [22, 25, 29],
    res: [19, 22, 25],
    hpMin:[16, 17, 18],
    atkMin:[6, 7, 8],
    spdMin:[8, 9, 10],
    defMin:[5, 6, 7],
    resMin:[4, 5, 6],
    weaponIndex: 7,
    movementIndex: 0 
  },
  jagen: {
    name: "Jagen",
    epithet: "Veteran Knight",
    image: "/images/hero-portraits/jagen.png",
    type: "Blue Lance",
    typeImg: "/images/weapon-icons/blue-lance.png",
    movement: "cavalry",
    movementImg: "/images/movement-icons/cavalry.png",
    weapon: 15,
    weaponName: "Silver Lance+",
    special: "Aegis",
    skillA: "Fury 3",
    skillC: "Fortify Cavalry",
    hp: [34, 37, 40],
    atk: [24, 27, 31],
    spd: [21, 24, 27],
    def: [22, 25, 28],
    res: [32, 35, 38],
    hpMin:[19, 20, 21],
    atkMin:[7, 8, 9],
    spdMin:[6, 7, 8],
    defMin:[7, 8,9],
    resMin:[10, 11, 12],
    weaponIndex: 1,
    movementIndex: 1
  },
  jakob: {
    name: "Jakob",
    epithet: "Devoted Servant",
    image: "/images/hero-portraits/jakob.png",
    type: "Dagger",
    typeImg: "/images/weapon-icons/dagger.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 10,
    weaponName: "Silver Dagger+",
    assist: "Rally Resistance",
    skillA: "Defense +3",
    skillB: "Renewal 3",
    hp: [35, 39, 42],
    atk: [25, 29, 32],
    spd: [27, 31, 34],
    def: [22, 25, 29],
    res: [21, 24, 28],
    hpMin:[16, 17, 18],
    atkMin:[6, 7, 8],
    spdMin:[8, 9, 10],
    defMin:[5, 6 ,7],
    resMin:[4, 5, 6],
    weaponIndex: 7,
    movementIndex: 0
  },
  jakob_hw: {
    name: "Jakob",
    epithet: "Devoted Monster",
    image: "/images/hero-portraits/jakob_hw.png",
    type: "Bow",
    typeImg: "/images/weapon-icons/bow.png",
    movement: "armored",
    movementImg: "/images/movement-icons/armored.png",
    weapon: 12,
    weaponName: "Monstrous Bow+",
    special: "Ignis",
    skillA: "Bracing Blow 2",
    skillB: "Wary Fighter 3",
    hp: [38, 42, 45],
    atk: [32, 35, 38],
    spd: [20, 23, 26],
    def: [30, 33, 36],
    res: [29, 32, 35],
    hpMin:[19, 20, 21],
    atkMin:[8, 9, 10],
    spdMin:[5, 6, 7],
    defMin:[8, 9, 10],
    resMin:[7, 8, 9],
    weaponIndex: 6,
    movementIndex: 3
  },
  /* 
  : {
    name: "",
    epithet: "",
    image: "/images/hero-portraits/.png",
    type: "",
    typeImg: "/images/weapon-icons/.png",
    movement: "",
    movementImg: "/images/movement-icons/.png",
    weapon: ,
    weaponName: ,
    hp: [],
    atk: [],
    spd: [],
    def: [],
    res: [],
    hpMin:[],
    atkMin:[],
    spdMin:[],
    defMin:[],
    resMin:[],
    weaponIndex: ,
    movementIndex: 
  },
*/
  sharena: {
    name: "Sharena",
    epithet: "Princess of Askr",
    image: "/images/hero-portraits/sharena.png",
    type: "Blue Lance",
    typeImg: "/images/weapon-icons/blue-lance.png",
    movement: "Infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 16,
    weaponName: "Fensalir",
    assist: "Rally Attack",
    skillA: "Speed +3",
    skillC: "Fortify Def 3",
    hp: [43, 43, 43],
    atk: [32, 32, 32],
    spd: [32, 32, 32],
    def: [29, 29, 29],
    res: [22, 22, 22],
    hpMin: [19, 19, 19],
    atkMin: [8, 8, 8],
    spdMin: [8, 8, 8],
    defMin: [7, 7, 7],
    resMin: [5, 5, 5],
    weaponIndex: 1,
    movementIndex: 0
  }
};

export default heroes;
