const heroes = {
  abel: {
    name: "Abel",
    epithet: "The Panther",
    image: "/images/hero-portraits/abel.png",
    type: "Blue Lance",
    typeImg: "/images/weapon-icons/blue-lance.png",
    movement: "Cavalry",
    movementImg: "/images/movement-icons/cavalry.png",
    weapon: 8,
    atkBonus: true,
    hp: [35, 39, 42],
    atk: [30, 33, 36],
    spd: [29, 32, 35],
    def: [22, 25, 28],
    res: [22, 25, 29]
  },
  alfonse: {
    name: "Alfonse",
    epithet: "Prince of Askr",
    image: "/images/hero-portraits/alfonse.png",
    type: "Red Sword",
    typeImg: "/images/weapon-icons/red-sword.png",
    movement: "Infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 16,
    hp: [43, 43, 43],
    atk: [35, 35, 35],
    spd: [25, 25, 25],
    def: [32, 32, 32],
    res: [22, 22, 22]
  },
  alm: {
    name: "Alm",
    epithet: "Hero of Prophecy",
    image: "/images/hero-portraits/alm.png",
    type: "Red Sword",
    typeImg: "/images/weapon-icons/red-sword.png",
    movement: "Infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 16,
    hp: [42, 45, 48],
    atk: [30, 33, 36],
    spd: [27, 30, 33],
    def: [24, 28, 31],
    res: [19, 22, 25]
  },
  amelia: {
    name: "Amelia",
    epithet: "Rose of the War",
    image: "/images/hero-portraits/amelia.png",
    type: "Green Axe",
    typeImg: "/images/weapon-icons/green-axe.png",
    movement: "armored",
    movementImg: "/images/movement-icons/armored.png",
    weapon: 14,
    hp: [44, 47, 50],
    atk: [31, 34, 37],
    spd: [31, 34, 37],
    def: [32, 35, 38],
    res: [20, 23, 27]
  },
  anna: {
    name: "Anna",
    epithet: "Commander",
    image: "/images/hero-portraits/anna.png",
    type: "Green Axe",
    typeImg: "/images/weapon-icons/green-axe.png",
    movement: "Infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 16,
    hp: [41, 41, 41],
    atk: [29, 29, 29],
    spd: [38, 38, 38],
    def: [22, 22, 22],
    res: [28, 28, 28]
  },
  arden: {
    name: "Arden",
    epithet: "Strong and Tough",
    image: "/images/hero-portraits/arden.png",
    type: "Red Sword",
    typeImg: "/images/weapon-icons/red-sword.png",
    movement: "Armored",
    movementImg: "/images/movement-icons/armored.png",
    weapon: 8,
    hp: [60, 60, 60],
    atk: [36, 36, 36],
    spd: [16, 16, 16],
    def: [41, 41, 41],
    res: [16, 16, 16]
  },
  arthur: {
    name: "Arthur",
    epithet: "Hapless Hero",
    image: "/images/hero-portraits/arthur.png",
    type: "Green Axe",
    typeImg: "/images/weapon-icons/green-axe.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 12,
    hp: [40, 43, 46],
    atk: [29, 32, 35],
    spd: [25, 29, 32],
    def: [26, 30, 33],
    res: [21, 24, 28]
  },
  arvis: {
    name: "Arvis",
    epithet: "Emperor of Flame",
    image: "/images/hero-portraits/arvis.png",
    type: "Red Tome",
    typeImg: "/images/weapon-icons/red-tome.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 14,
    hp: [33, 33, 33],
    atk: [34, 34, 34],
    spd: [31, 31, 31],
    def: [17, 17, 17],
    res: [33, 33, 33]
  },
  athena: {
    name: "Athena",
    epithet: "Borderland Sword",
    image: "/images/hero-portraits/athena.png",
    type: "Red Sword",
    typeImg: "/images/weapon-icons/red-sword.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 13,
    hp: [33, 36, 40],
    atk: [28, 31, 34],
    spd: [35, 38, 41],
    def: [24, 27, 28],
    res: [21, 24, 28]
  },
  ayra: {
    name: "Ayra",
    epithet: "Astra's Wielder",
    image: "/images/hero-portraits/ayra.png",
    type: "Red Sword",
    typeImg: "/images/weapon-icons/red-sword.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 16,
    spdBonus: true,
    hp: [37, 41, 44],
    atk: [30, 33, 36],
    spd: [34, 37, 40],
    def: [28, 31, 34],
    res: [18, 21, 24]
  },
  azama: {
    name: "Azama",
    epithet: "Carefree Monk",
    image: "/images/hero-portraits/azama.png",
    type: "Staff",
    typeImg: "/images/weapon-icons/staff.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 10,
    hp: [40, 43, 46],
    atk: [18, 21, 24],
    spd: [23, 26, 30],
    def: [29, 32, 35],
    res: [22, 25, 29]
  },
  azura: {
    name: "Azura",
    epithet: "Lady of the Lake",
    image: "/images/hero-portraits/azura.png",
    type: "Blue Lance",
    typeImg: "/images/weapon-icons/blue-lance.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 12,
    hp: [33, 36, 40],
    atk: [28, 31, 34],
    spd: [30, 33, 36],
    def: [18, 21, 24],
    res: [24, 28, 31]
  },
  azura_ny: {
    name: "Azura",
    epithet: "Celebratory Spirit",
    image: "/images/hero-portraits/azura_ny.png",
    type: "Green Axe",
    typeImg: "/images/weapon-icons/green-axe.png",
    movement: "flying",
    movementImg: "/images/movement-icons/flying.png",
    weapon: 14,
    hp: [33, 37, 40],
    atk: [27, 30, 33],
    spd: [32, 35, 38],
    def: [19, 22, 25],
    res: [22, 26, 29]
  },
  azura_pa: {
    name: "Azura",
    epithet: "Lady of Ballads",
    image: "/images/hero-portraits/azura_pa.png",
    type: "Green Axe",
    typeImg: "/images/weapon-icons/green-axe.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 16,
    hp: [32, 35, 39],
    atk: [29, 32, 35],
    spd: [31, 34, 37],
    def: [17, 20, 23],
    res: [24, 28, 31]
  },
  barst: {
    name: "Barst",
    epithet: "The Hatchet",
    image: "/images/hero-portraits/barst.png",
    type: "Green Axe",
    typeImg: "/images/weapon-icons/green-axe.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 8,
    hp: [43, 46, 49],
    atk: [30, 33, 36],
    spd: [29, 32, 35],
    def: [27, 30, 33],
    res: [13, 17, 20]
  },
  bartre: {
    name: "Bartre",
    epithet: "Fearless Warrior",
    image: "/images/hero-portraits/bartre.png",
    type: "Green-Axe",
    typeImg: "/images/weapon-icons/green-axe.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 12,
    hp: [46, 49, 52],
    atk: [33, 36, 39],
    spd: [22, 25, 29],
    def: [30, 33, 36],
    res: [10, 13, 17]
  },
  berkut: {
    name: "Berkut",
    epithet: "Prideful Prince",
    image: "/images/hero-portraits/berkut.png",
    type: "Blue Lance",
    typeImg: "/images/weapon-icons/blue-lance.png",
    movement: "cavalry",
    movementImg: "/images/movement-icons/cavalry.png",
    weapon: 14,
    hp: [43, 43, 43],
    atk: [34, 34, 34],
    spd: [22, 22, 22],
    def: [31, 31, 31],
    res: [24, 24, 24]
  },
  beruka: {
    name: "Beruka",
    epithet: "Quiet Assassin",
    image: "/images/hero-portraits/beruka.png",
    type: "Green Axe",
    typeImg: "/images/weapon-icons/green-axe.png",
    movement: "Flying",
    movementImg: "/images/movement-icons/flying.png",
    weapon: 11,
    hp: [43, 46, 49],
    atk: [25, 29, 32],
    spd: [20, 23, 26],
    def: [34, 37, 40],
    res: [19, 22, 25]
  },
  blackKnight: {
    name: "Black Knight",
    epithet: "Sinister General",
    image: "/images/hero-portraits/blackKnight.png",
    type: "Red Sword",
    typeImg: "/images/weapon-icons/red-sword.png",
    movement: "armored",
    movementImg: "/images/movement-icons/armored.png",
    weapon: 16,
    hp: [48, 48, 48],
    atk: [34, 34, 34],
    spd: [34, 34, 34],
    def: [35, 35, 35],
    res: [18, 18, 18]
  },
  boey: {
    name: "Boey",
    epithet: "Skillful Survivor",
    image: "/images/hero-portraits/boey.png",
    type: "Green Tome",
    typeImg: "/images/weapon-icons/green-tome.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 10,
    hp: [40, 43, 46],
    atk: [25, 29, 32],
    spd: [23, 27, 30],
    def: [29, 32, 35],
    res: [14, 18, 21]
  },
  caeda: {
    name: "Caeda",
    epithet: "Talys's Heart",
    image: "/images/hero-portraits/caeda.png",
    type: "Red Sword",
    typeImg: "/images/weapon-icons/red-sword.png",
    movement: "flying",
    movementImg: "/images/movement-icons/Flying.png",
    weapon: 12,
    hp: [33, 36, 40],
    atk: [22, 25, 29],
    spd: [34, 37, 40],
    def: [21, 24, 28],
    res: [31, 34, 37]
  },
  caeda_bb: {
    name: "Caeda",
    epithet: "Talys's Bride",
    image: "/images/hero-portraits/caeda_bb.png",
    type: "Blue Tome",
    typeImg: "/images/weapon-icons/blue-tome.png",
    movement: "infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 12,
    hp: [30, 33, 36],
    atk: [25, 29, 32],
    spd: [34, 37, 40],
    def: [16, 19, 22],
    res: [26, 30, 33]
  },
  cain: {
    name: "Cain",
    epithet: "The Bull",
    image: "/images/hero-portraits/cain.png",
    type: "Red Sword",
    typeImg: "/images/weapon-icons/red-sword.png",
    movement: "cavalry",
    movementImg: "/images/movement-icons/cavalry.png",
    weapon: 8,
    hp: [39, 42, 45],
    atk: [29, 32, 35],
    spd: [29, 32, 35],
    def: [24, 27, 31],
    res: [18, 21, 24]
  },
  camilla: {
    name: "Camilla",
    epithet: "Bewitching Beauty",
    image: "/images/hero-portraits/camilla.png",
    type: "Green Axe",
    typeImg: "/images/weapon-icons/green-axe.png",
    movement: "flying",
    movementImg: "/images/movement-icons/flying.png",
    weapon: 8,
    hp: [34, 37, 41],
    atk: [26, 30, 33],
    spd: [29, 32, 35],
    def: [24, 28, 31],
    res: [28, 31, 34]
  },
  camilla_ny: {
    name: "Camilla",
    epithet: "Holiday Traveler",
    image: "/images/hero-portraits/camilla_ny.png",
    type: "Red Sword",
    typeImg: "/images/weapon-icons/red-sword.png",
    movement: "flying",
    movementImg: "/images/movement-icons/flying.png",
    weapon: 14,
    hp: [36, 40, 43],
    atk: [30, 33, 36],
    spd: [32, 35, 38],
    def: [28, 31, 34],
    res: [20, 23, 27]
  },
  fjorm: {
    name: "Fjorm",
    epithet: "Princess of Ice",
    image: "/images/hero-portraits/fjorm.png",
    type: "Blue Lance",
    typeImg: "/images/weapon-icons/blue-lance.png",
    movement: "Infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 16,
    hp: [35, 39, 42],
    atk: [26, 30, 33],
    spd: [28, 31, 34],
    def: [26, 30, 33],
    res: [31, 34, 37]
  },
  sharena: {
    name: "Sharena",
    epithet: "Princess of Askr",
    image: "/images/hero-portraits/sharena.png",
    type: "Blue Lance",
    typeImg: "/images/weapon-icons/blue-lance.png",
    movement: "Infantry",
    movementImg: "/images/movement-icons/infantry.png",
    weapon: 16,
    hp: [43, 43, 43],
    atk: [32, 32, 32],
    spd: [32, 32, 32],
    def: [29, 29, 29],
    res: [22, 22, 22]
  }
};

/* 
  : {
    name: "",
    epithet: "",
    image: "/images/hero-portraits/.png",
    type: "",
    typeImg: "/images/weapon-icons/.png",
    movement: "",
    movementImg: "/images/movement-icons/.png",
    weapon: ,
    hp: [],
    atk: [],
    spd: [],
    def: [],
    res: []
  },
*/

export default heroes;
